# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.packages = QtWidgets.QTableWidget(self.centralwidget)
        self.packages.setMinimumSize(QtCore.QSize(521, 271))
        self.packages.setMaximumSize(QtCore.QSize(10000, 10000))
        self.packages.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.packages.setAutoScroll(True)
        self.packages.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.packages.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.packages.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.packages.setWordWrap(True)
        self.packages.setObjectName("packages")
        self.packages.setColumnCount(6)
        self.packages.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.packages.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.packages.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.packages.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.packages.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.packages.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.packages.setHorizontalHeaderItem(5, item)
        self.horizontalLayout.addWidget(self.packages)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.pip = QtWidgets.QAction(MainWindow)
        self.pip.setCheckable(True)
        self.pip.setChecked(False)
        self.pip.setEnabled(True)
        self.pip.setObjectName("pip")
        self.npm = QtWidgets.QAction(MainWindow)
        self.npm.setCheckable(True)
        self.npm.setObjectName("npm")
        self.all_packages = QtWidgets.QAction(MainWindow)
        self.all_packages.setCheckable(True)
        self.all_packages.setChecked(True)
        self.all_packages.setEnabled(False)
        self.all_packages.setObjectName("all_packages")
        self.outdated_packages = QtWidgets.QAction(MainWindow)
        self.outdated_packages.setCheckable(True)
        self.outdated_packages.setObjectName("outdated_packages")
        self.menu.addAction(self.pip)
        self.menu.addAction(self.npm)
        self.menu_2.addAction(self.all_packages)
        self.menu_2.addAction(self.outdated_packages)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PM (Package Manager)"))
        item = self.packages.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.packages.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Версия"))
        item = self.packages.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Описание"))
        item = self.packages.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Страница"))
        item = self.packages.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Автор"))
        item = self.packages.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Лицензия"))
        self.menu.setTitle(_translate("MainWindow", "Пакетный менеджер"))
        self.menu_2.setTitle(_translate("MainWindow", "Показ"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.pip.setText(_translate("MainWindow", "PiPy (pip3)"))
        self.npm.setText(_translate("MainWindow", "NPM"))
        self.all_packages.setText(_translate("MainWindow", "Все пакеты"))
        self.outdated_packages.setText(_translate("MainWindow", "Пакеты, которые можно обновить"))
